#!/bin/bash
#
#
# Caddy Web Server Installer
#
#

# Global config
caddyname="Caddy Web Server"
caddypath="/opt/caddyserver"
caddyuser="caddy"
caddyfile="/etc/Caddyfile"
caddywww="/var/caddywww"
caddylog="/var/log/caddy"

about () {
	echo ""
	echo "  ========================================================= "
	echo "  \             Caddy Web Server Installer                / "
	echo "  \             V 1.4 (beta)  (27 Mar 2016)               / "
	echo "  \             Created by Sayem Chowdhury                / "
	echo "  \             Caddy Web: Caddyserver.com                / "
	echo "  ========================================================= "
	echo ""
}

howto () {
	echo "  Welcome!"
	echo "  run 'caddy help' for help"
	echo ""
}

prms () {
	echo "  caddy start          - Start $caddyname"
	echo "  caddy stop           - Stop/Shutdown $caddyname"
	echo "  caddy restart        - Restart $caddyname"
	echo "  caddy status         - Check $caddyname running or not"
	echo "  caddy install        - Install $caddyname on fresh OS"
	echo "  caddy delete         - Uninstall Caddy and data."
	echo "  caddy about          - About Caddy Web Server Installer"
	echo ""
}

startcaddy () {
	pids=`ps aux | grep $caddypath/caddy | grep -v grep | awk '{ print $2 }'`
	if [ -z "$pids" ] ; then
		echo "$(tput setaf 2)Starting$(tput sgr0) $caddyname..."
		sudo -H -u $caddyuser $caddypath/caddy -conf="$caddyfile" -quiet=true &
		echo " Done."
	else
		echo "  $caddyname is already $(tput setaf 2)running$(tput sgr0) on: $pids (PID)"
	fi
}

stopcaddy () {
	pids=`ps aux | grep $caddypath/caddy | grep -v grep | awk '{ print $2 }' | sort -r`
	if [ -z "$pids" ] ; then
		echo ""
		echo "  $caddyname is $(tput setaf 1)NOT running$(tput sgr0)"
		echo ""
	else
		echo ""
		echo "  $(tput setaf 1)Shutting down$(tput sgr0) $caddyname..."
		kill $pids
		rm -f $pids
		echo "  Done."
	fi
}

caddystatus () {
	pids=`ps aux | grep $caddypath/caddy | grep -v grep | awk '{ print $2 }'`
	if [[ ! -e $caddypath/caddy ]]; then
	echo ""
	echo "  Caddy is not installed."
	echo "  run 'caddy install' to install Caddy"
	echo ""
	exit
	fi
	#Detect Caddy process
	if [ -z "$pids" ] ; then
		echo ""
		echo "  $caddyname is $(tput setaf 1)NOT running$(tput sgr0)"
	else
		caddymemusage=`ps axo rss,comm,pid | grep $pids | awk '{$1/=1024;printf "%.0fMB\t",$1}{print $2}' | awk '{print $1}'`
		echo ""
		echo "  $caddyname is $(tput setaf 2)running$(tput sgr0)"
		echo "  Caddy (PID: $pids) is using $caddymemusage RAM"
	fi
	echo ""
}

installcaddy () {
	cpubits=`uname -m`
	#Detetcting Caddy installed or not
	if [[ -e "$caddypath/caddy" ]]; then
		echo ""
		echo "  $caddyname is already installed on"
		echo "  $caddypath/caddy"
		echo ""
		exit
		echo ""
	fi
	#Detecting ARM
	if [ "$cpubits" == 'armeabi-v7a' ]; then
	echo ""
	echo "  Sorry! Your system is ARM based."
	echo "  Perhaps Caddyserver.com have tutorial for you."
	exit
	fi
	#Installing Caddy
	echo ""
	echo "  Caddy Web Server Installer"
	if [ "$cpubits" == 'x86_64' ]; then
	echo "  Downloading $caddyname (64bit)" #Caddy linux 64bit
	wget -q "https://caddyserver.com/download/build?os=linux&arch=amd64&features=" -O "caddy_linux_custom.tar.gz"
	else
	echo "  Downloading $caddyname (32bit)" #Caddy linux 32bit
	wget -q "https://caddyserver.com/download/build?os=linux&arch=386&features=" -O "caddy_linux_custom.tar.gz"
	fi
	#Creating folders
	echo ""
	mkdir -p $caddypath
	mkdir -p $caddylog
	#Extract Caddy on created folder
	echo "  Extracting $caddyname to $caddypath"
	tar xzf caddy_linux_custom.tar.gz -C $caddypath #Extracting Caddy
	echo "  Caddy has been extracted to directory $caddypath"
	setcap cap_net_bind_service=+ep $caddypath/caddy
	rm -rf caddy_linux_custom.tar.gz #Deleting Caddy archive
	echo ""
	#Creating non-root user
	useradd -r -d $caddypath -s /bin/false $caddyuser
	chown $caddyuser $caddypath
	chown $caddyuser $caddylog
	#Installing required php files
	echo "  Installing required php files"
	echo "  Installing php5-fpm php5-cli curl..."
	#Detecting apt-get/yum
	aptcheck=`[ -e /usr/bin/apt-get ] && echo "Found" || echo "Not"`
	if [ "$aptcheck" == 'Found' ]; then
	apt-get install php5-fpm php5-cli curl -y &>/dev/null
	else
	yum install php5-fpm php5-cli curl -y &>/dev/null
	fi
	echo "  Installed"
}

caddyfile () {
	#Generate Caddyfile
	mkdir -p $caddywww
	chown $caddyuser $caddywww
	echo ""
	echo "  Enter your domain name"
	read -p "  Domain name: " domainname
	echo "$domainname
root $caddywww
gzip
log $caddylog/access.log
errors $caddylog/error.log
fastcgi / /var/run/php5-fpm.sock php" >> $caddyfile

	#Generate example html
	echo "<TITLE>Caddy Default Page</TITLE>

<h1><font color="green">It works!</font></h1>

<h3><font color="grey">This is the default welcome page used to test the correct operation of the Caddy web server after installation via Caddy Web Server Installer.</font></h3>

<h3><font color="grey">If you can read this page, it means that the Caddy web server installed at this site is working properly.<br>
You should <font color="#D03C3C">replace this file</font>
(located at <tt>$caddywww/index.html</tt>) before continuing to operate your server.</font></h3>
</hr>
<h3><font color="grey">If you are a normal user of this web site and don't know what this page is about, this probably means that the site is currently unavailable due to maintenance.</font></h3>" >> $caddywww/index.html
	echo "  Done. Caddy has been installed"
	echo ""

}

deletecaddy () {
	if [[ -e  "$caddypath" ]] ; then
		echo ""
		echo "  Are you sure you want to delete caddy?"
		echo "                 1) YES"
		echo "                 2) NO"
		read -p "  Select an option: " option
		case $option in
			1)
			echo ""
			rm -rf $caddypath #deleting caddy web server folder
			rm $caddyfile #deleting caddyfile
			rm -rf $caddywww #deleting caddy html folder
			userdel $caddyuser #delete caddy user
			echo "  Caddy has been deleted"
			echo ""
			exit
			;;
			2) exit;;
		esac
		else
		echo ""
		echo "  Looks like Caddy is not installed"
	fi
	echo ""
}

versioninfo () {
	echo "  Caddy-Web-Server-Installer - v1.4 (beta)"
	echo "  $caddyname $caddypath/caddy -version | awk '{print $2}'"
	echo "  php5-fpm -v | grep built"
	echo ""
}

# See how we were called.
case $1 in
	'-start'|'start' )
		startcaddy;;
	'-stop'|'stop' )
		stopcaddy;;
	'-restart'|'restart'|'-reload'|'reload' )
		stopcaddy; startcaddy;;
	'-status'|'status' )
		caddystatus;;
	'-install'|'install' )
		installcaddy; caddyfile;;
	'-del'|'delete'|'-rm' )
		deletecaddy;;
	'-about'|'about' )
		about;;
	'-h'|'help' )
		prms;;
	'-v'|'version'|'-version' )
		versioninfo;;
	*)
		caddystatus; howto;;
esac
