#!/bin/bash
#
#
# Caddy Web Server Installer
#
#

# Global config
caddyname="Caddy Web Server"
caddypath="/opt/caddyserver"
caddyuser="caddy"
caddyfile="/etc/Caddyfile"
caddywww="/var/caddywww"
caddylog="/var/log/caddy"
caddymail="your@email.com"
cwsiv="v2.1 beta (28 Mar 2016)"

about () {
	echo ""
	echo "  ========================================================= "
	echo "  \             Caddy Web Server Installer                / "
	echo "  \               $cwsiv                 / "
	echo "  \             Created by Sayem Chowdhury                / "
	echo "  \             Caddy Web: Caddyserver.com                / "
	echo "  ========================================================= "
	echo ""
}

howto () {
	echo "  Welcome!"
	echo "  run $(tput setaf 3)caddy help $(tput sgr0) for help"
	echo ""
}

prms () {
	echo "  caddy start          - Start $caddyname"
	echo "  caddy stop           - Stop/Shutdown $caddyname"
	echo "  caddy restart        - Restart $caddyname"
	echo "  caddy status         - Check $caddyname running or not"
	echo "  caddy install        - Install $caddyname on fresh OS"
	echo "  caddy update         - Update $caddyname"
	echo "  caddy delete         - Uninstall Caddy and data."
	echo "  caddy about          - About Caddy Web Server Installer"
	echo ""
}

startcaddy () {
	pids=`ps aux | grep $caddypath/caddy | grep -v grep | awk '{ print $2 }'`
	if [ -z "$pids" ] ; then
		echo ""
		echo -n "  Starting $caddyname..."
		sudo -H -u $caddyuser $caddypath/caddy -conf="$caddyfile" -quiet=true &
		echo "  $(tput setaf 2)DONE$(tput sgr0)"
		echo ""
	else
		echo ""
		echo "  $caddyname is already $(tput setaf 2)running$(tput sgr0) on: $pids (PID)"
		echo ""
	fi
}

stopcaddy () {
	pids=`ps aux | grep $caddypath/caddy | grep -v grep | awk '{ print $2 }' | sort -r`
	if [ -z "$pids" ] ; then
		echo ""
		echo "  $caddyname is $(tput setaf 1)NOT running$(tput sgr0)"
		echo ""
	else
		echo ""
		echo -n "  Shutting down $caddyname..."
		kill $pids
		rm -f $pids
		echo "  $(tput setaf 2)DONE$(tput sgr0)"
		echo ""
	fi
}

caddystatus () {
	pids=`ps aux | grep $caddypath/caddy | grep -v grep | awk '{ print $2 }'`
	if [[ ! -e $caddypath/caddy ]]; then
	echo ""
	echo "  Caddy is not installed."
	echo "  run $(tput setaf 3)caddy install$(tput sgr0) to install $caddyname"
	echo ""
	exit
	fi
	#Detect Caddy process
	if [ -z "$pids" ] ; then
		echo ""
		echo "  $caddyname is $(tput setaf 1)NOT running$(tput sgr0)"
	else
		caddymemusage=`ps axo rss,comm,pid | grep $pids | awk '{$1/=1024;printf "%.0fMB\t",$1}{print $2}' | awk '{print $1}'`
		echo ""
		echo "  $caddyname is $(tput setaf 2)running$(tput sgr0)"
		echo "  Caddy (PID: $pids) is using $caddymemusage RAM"
	fi
	echo ""
}

installcaddy () {
	cpubits=`uname -m`
	#Detetcting Caddy installed or not
	if [[ -e "$caddypath/caddy" ]]; then
		echo ""
		echo "  $caddyname is already installed on"
		echo "  $caddypath/caddy"
		echo ""
		exit
		echo ""
	fi
	#Detecting ARM
	if [ "$cpubits" == 'armeabi-v7a' ]; then
	echo ""
	echo "  Sorry! Your system is ARM based."
	echo "  Perhaps Caddyserver.com have tutorial for you."
	exit
	fi
	#Installing Caddy
	echo ""
	echo "  Caddy Web Server Installer"
	if [ "$cpubits" == 'x86_64' ]; then
	echo -n "  Downloading $caddyname (64bit)..." #Caddy linux 64bit
	wget -q "https://caddyserver.com/download/build?os=linux&arch=amd64&features=" -O "caddy_linux_custom.tar.gz"
	echo "  $(tput setaf 2)DONE$(tput sgr0)"
	else
	echo -n "  Downloading $caddyname (32bit)..." #Caddy linux 32bit
	wget -q "https://caddyserver.com/download/build?os=linux&arch=386&features=" -O "caddy_linux_custom.tar.gz"
	echo "  $(tput setaf 2)DONE$(tput sgr0)"
	fi
	#Creating folders
	echo ""
	mkdir -p $caddypath
	mkdir -p $caddylog
	#Extract Caddy on created folder
	echo -n "  Extracting $caddyname to $caddypath..."
	tar xzf caddy_linux_custom.tar.gz -C $caddypath #Extracting Caddy
	echo " $(tput setaf 2)DONE$(tput sgr0)"
	setcap cap_net_bind_service=+ep $caddypath/caddy
	rm -rf caddy_linux_custom.tar.gz #Deleting Caddy archive
	echo ""
	#Creating non-root user
	useradd -r -d $caddypath -s /bin/false $caddyuser
	chown $caddyuser $caddypath
	chown $caddyuser $caddylog
	#Installing required php files
	echo "  Installing required php files"
	echo "  Installing php5-fpm php5-cli curl..."
	#Detecting apt-get/yum
	aptcheck=`[ -e /usr/bin/apt-get ] && echo "Found" || echo "Not"`
	if [ "$aptcheck" == 'Found' ]; then
	apt-get install php5-fpm php5-cli curl -y &>/dev/null
	else
	yum install php-fpm php-cli curl -y &>/dev/null
	fi
	echo "  Installed"
}

caddyfile () {
	#Check if Caddyfile exist
	#Generate Caddyfile
	if [[ ! -e $caddyfile ]]; then
	echo ""
	echo "  Enter your domain name"
	read -p "  Domain name: " domainname
	echo "$domainname
tls $caddymail
root $caddywww
gzip
log $caddylog/access.log
errors $caddylog/error.log
fastcgi / /var/run/php5-fpm.sock php" >> $caddyfile
	echo "  Caddyfile created"
	else
	echo "  Caddyfile found. Skip... "
	fi
	#Check if caddywww exist
	if [[ ! -e $caddywww ]]; then
	mkdir -p $caddywww
	chown $caddyuser $caddywww
	fi
	#Generate example html
	if [[ ! -e $caddywww/index.html ]]; then
	echo "<TITLE>Caddy Default Page</TITLE>

<h1><font color="green">It works!</font></h1>

<h3><font color="grey">This is the default welcome page used to test the correct operation of the Caddy web server after installation via Caddy Web Server Installer.</font></h3>

<h3><font color="grey">If you can read this page, it means that the Caddy web server installed at this site is working properly.<br>
You should <font color="#D03C3C">replace this file</font>
(located at <tt>$caddywww/index.html</tt>) before continuing to operate your server.</font></h3>
</hr>
<h3><font color="grey">If you are a normal user of this web site and don't know what this page is about, this probably means that the site is currently unavailable due to maintenance.</font></h3>" >> $caddywww/index.html
	echo "  index.html created"
	else
	echo "  index.html found. Skip ... "
	fi
	echo "  Done. Caddy has been installed :)"
	echo "  Run $(tput setaf 3)caddy start$(tput sgr0) to start $caddyname"
	echo ""

}

updatecaddy () {
	#Detetcting Caddy installed or not
	if [[ ! -e "$caddypath/caddy" ]]; then
		echo ""
		echo "  $caddyname is not installed"
		sleep 0.2
		echo "  run $(tput setaf 3)caddy install$(tput sgr0) to install $caddyname"
		echo ""
		exit
		echo ""
	fi
	#Detecting ARM
	if [ "$cpubits" == 'armeabi-v7a' ]; then
	echo ""
	echo "  Sorry! Your system is ARM based."
	echo "  Perhaps Caddyserver.com have tutorial for you."
	exit
	fi
	#Updating Caddy
	caddyserverversion=`$caddypath/caddy -version | awk '{print}'`
	cpubits=`uname -m`
	echo ""
	echo "  Found $caddyserverversion"
	if [ "$cpubits" == 'x86_64' ]; then
	echo "  Downloading $caddyname (64bit)" #Caddy linux 64bit
	wget -q "https://caddyserver.com/download/build?os=linux&arch=amd64&features=" -O "caddy_linux_custom.tar.gz"
	else
	echo "  Downloading $caddyname (32bit)" #Caddy linux 32bit
	wget -q "https://caddyserver.com/download/build?os=linux&arch=386&features=" -O "caddy_linux_custom.tar.gz"
	fi
	echo "  Done"
	sleep 0.1
	#Delete Caddy folder
	echo "  Removing Caddy directory $caddypath"
	sleep 0.3
	rm -rf $caddypath/*
	echo "  Done"
	sleep 0.1
	#Extract Caddy on created folder
	echo "  Extracting $caddyname to $caddypath"
	tar xzf caddy_linux_custom.tar.gz -C $caddypath #Extracting Caddy
	echo "  Done"
	setcap cap_net_bind_service=+ep $caddypath/caddy
	rm -rf caddy_linux_custom.tar.gz #Deleting Caddy archive
	echo ""
	echo "  Updated $caddyserverversion"
	echo ""
}

deletecaddy () {
	if [[ -e  "$caddypath" ]] ; then
		echo ""
		echo "  Are you sure you want to delete caddy?"
		echo "                 1) YES"
		echo "                 2) NO"
		read -p "  Select an option: " option
		case $option in
			1)
			echo ""
			rm -rf $caddypath #deleting caddy web server folder
			rm $caddyfile #deleting caddyfile
			rm -rf $caddywww #deleting caddy html folder
			userdel $caddyuser #delete caddy user
			echo "  Caddy has been deleted"
			echo ""
			exit
			;;
			2) exit;;
		esac
		else
		echo ""
		echo "  Looks like Caddy is not installed"
	fi
	echo ""
}

versioninfo () {
	caddyserverversion=`$caddypath/caddy -version | awk '{print $2}'`
	php5fpmversion=`php5-fpm -v | grep built`
	echo ""
	echo "  $caddyname $caddyserverversion"
	echo "  Caddy Web Server Installer - $cwsiv"
	echo "  $php5fpmversion"
	echo ""
}

# See how we were called.
case $1 in
	'-start'|'start' )
		startcaddy;;
	'-stop'|'stop' )
		stopcaddy;;
	'-restart'|'restart'|'-reload'|'reload' )
		stopcaddy; startcaddy;;
	'-status'|'status' )
		caddystatus;;
	'-install'|'install' )
		installcaddy; caddyfile;;
	'-update'|'update' )
		updatecaddy;;
	'-del'|'delete'|'-rm' )
		deletecaddy;;
	'-about'|'about' )
		about;;
	'-h'|'help' )
		prms;;
	'-v'|'version'|'-version' )
		versioninfo;;
	*)
		caddystatus; howto;;
esac
exit 1
